### ISSUE TITLE
Visual follow-line

### ISSUE THREAD

**Issue by mohamedsayed18** [JdeRobot/jderobot.github.io#102]
I think these lines in the [visual follow-line exercise](https://jderobot.github.io/RoboticsAcademy/portfolio/follow_line/)
echo 'source /opt/jderobot/share/jderobot/gazebo/gazebo-setup.sh' > ~/.bashrc
echo 'source /opt/jderobot/share/jderobot/gazebo/gazebo-assets-setup.sh' > ~/.bashrc
are meant to append not to overwirte so they need to be changed to >> instead of >
echo 'source /opt/jderobot/share/jderobot/gazebo/gazebo-setup.sh' >> ~/.bashrc
echo 'source /opt/jderobot/share/jderobot/gazebo/gazebo-assets-setup.sh' >> ~/.bashrc
I can do a pullrequest with those changes  but i don't how to get the page to modifiy (not familiar with web technologies)

**Comment by jmplaza** [comment]
Hi @mohamedsayed18 , 
no, it is a bad policy to replace the user's .bashrc. Maybe she has other relevant information or configuration there for her. It is better policy to append as it does not remove anything. In the worst case this expansion repeats information but that does not hurt. Everything keeps working.

**Comment by mohamedsayed18** [comment]
those two commands will even overwrite each other
and some important things will be overwritten like:
source /opt/jderobot/setup.bash
source /opt/ros/melodic/setup.bash
