### ISSUE TITLE
broken links for Gsoc 21 programming challanges

### ISSUE THREAD

**Issue by shreyas2000** [JdeRobot/jderobot.github.io#153]
the links for programming tests are broken here `_pages/activities/gsoc/2021.md`

**Comment by Jovian-Dsouza** [comment]
The links for programming challenges still seem to be broken

[https://gsyc.urjc.es/jmplaza/gsoc/gsoc2021-RoboticsAcademy-test.pdf](RoboticsAcademy-Challenge)

[https://gsyc.urjc.es/jmplaza/gsoc/gsoc2021-c++-test.pdf](C++Test)

[https://gsyc.urjc.es/jmplaza/gsoc/gsoc2021-python-test.pdf](Python-Test)

None of these links are working for me.
