### ISSUE TITLE
wiki.jderobot.org server seems to be down

### ISSUE THREAD

**Issue by Jovian-Dsouza** [JdeRobot/jderobot.github.io#158]
Unable to install Robotics-Academy (2.1 and 2.0 release).

Failing when installing `JdeRobot-base` . Getting this error when doing a `sudo apt update`

```
W: Failed to fetch http://wiki.jderobot.org/apt/dists/bionic/InRelease  Cannot initiate the connection to wiki.jderobot.org:80 (64:ff9b::c193:4f3c). - connect (101: Network is unreachable) Could not connect to wiki.jderobot.org:80 (193.147.79.60), connection timed out
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

Also I am unable to download the GSOC 2021 programming assignments. 

Is wiki.jderobot.org  site down?

**Comment by shivam675** [comment]
Facing the same issue. I guess sile is down indeed !

**Comment by jmplaza** [comment]
RoboticsAcademy 2.0 and 2.1 are DEPRECATED, please use only 2.3 (= web based templates). No dependency on JdeRobot-base is required any more.
