### ISSUE TITLE
GSOC 2021 programming challenge links still broken

### ISSUE THREAD

**Issue by Jovian-Dsouza** [JdeRobot/jderobot.github.io#159]
The links for programming challenges still seem to be broken

[https://gsyc.urjc.es/jmplaza/gsoc/gsoc2021-RoboticsAcademy-test.pdf](RoboticsAcademy-Challenge)

[https://gsyc.urjc.es/jmplaza/gsoc/gsoc2021-c++-test.pdf](C++Test)

[https://gsyc.urjc.es/jmplaza/gsoc/gsoc2021-python-test.pdf](Python-Test)

None of these links are working for me.

Refers #153

**Comment by jmplaza** [comment]
Hi @Jovian-Dsouza , check it again now. There were problems with our server and the DNS, it allowed access only from certain IPs... We've moved those files to another full public localtion.

**Comment by Jovian-Dsouza** [comment]
Yes the links are working now . Thanks @jmplaza
