### ISSUE TITLE
[Videos] - Pass videos from Wiki to Youtube.

### ISSUE THREAD

**Issue by vmartinezf** [JdeRobot/jderobot.github.io#59]
Some videos from the wiki aren't uploaded to YouTube:

*  https://wiki.jderobot.org/Programacion-avanzada-de-drones#PROGRAMA

* https://wiki.jderobot.org/Programacion-avanzada-de-drones#Pr.C3.A1ctica_2:_Escapando_de_un_laberinto_con_flechas_de_ayuda

* https://wiki.jderobot.org/Programacion-avanzada-de-drones#Pr.C3.A1ctica_3:_B.C3.BAsqueda_de_personas_tras_una_cat.C3.A1strofe

* http://wiki.jderobot.org/Programacion-de-drones#PROGRAMA

* http://wiki.jderobot.org/Programacion-de-drones#Pr.C3.A1ctica_Tu_cuadric.C3.B3ptero_sigue_una_carretera_desde_el_aire

**Comment by jmplaza** [comment]
They can now be found in YouTube: 

1a.  https://youtu.be/SGrTKwqr_Uw
1b. https://youtu.be/Ze92AmFn19Q
2. https://youtu.be/JR5OH_XHw7U
3. https://youtu.be/c0heCUeDm7I
4a = 1a
4b = 1b
5. https://youtu.be/-hcbU0POiWc
