### ISSUE TITLE
Better redirection from jderobot.org to jderobot.github.io

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/jderobot.github.io#86]
https://jderobot.org successfully points to https://jderobot.github.io
but nice addesses as https://jderobot.org/RoboticsAcademy do not resolve to  https://jderobot.github.io/RoboticsAcademy , they resolve to https://jderobot.github.ioroboticsacademy

Notice the missing /

**Comment by fqez** [comment]
Fixed :)
