### ISSUE TITLE
APT Repository not working.

### ISSUE THREAD

**Issue by rubenanapu** [JdeRobot/jderobot.github.io#93]
In order to install Jde Robot packages, I used to use the command below:

```
echo 'deb [arch=amd64] http://jderobot.org/apt xenial main' > /etc/apt/sources.list.d/jderobot.list
```

Some weeks ago it started breaking, so, after checking the documentation again, I changed the script by adding the **wiki.** prefix and it started working:

```
echo 'deb [arch=amd64] http://wiki.jderobot.org/apt xenial main' > /etc/apt/sources.list.d/jderobot.list
```

But today (20th of November, 2019), it started failing again.

The first error was:
> W: The repository 'http://wiki.jderobot.org/apt xenial Release' does not have a Release file

Then I tried `sudo apt-get update` again and then I had:

> Err:19 http://wiki.jderobot.org/apt xenial/main amd64 Packages                                                                               
> 502  Proxy Error

I then changed the main URL to `http://main.jderobot.org/apt xenial Release` (after checking the [recent commits](https://github.com/JdeRobot/jderobot.github.io/commit/7230ef2422eaa24cde4bcbfd35bcd700f28f0fa9)), then the error was:

> Could not resolve 'main.jderobot.org'

Then I tried `http://wiki.jderobot.io/apt xenial main` (also after checking the recent docs) and got:

> Could not resolve 'wiki.jderobot.io'

Also tried `http://main.jderobot.io/apt xenial main`, but the error below also came:
>  Could not resolve 'main.jderobot.io'

Is there anything we can do to solve this? Does anybody know whether the address was changed but the documentation was not updated?

**Comment by igarag** [comment]
Hello @rubenanapu.

Sorry for the late. Have you checked the installation again? We reviewed the steps and left them updated in the Robotics-Academy repository. Confirm me if you have the complete installation to review this issue.

Thank you.

**Comment by rubenanapu** [comment]
Hi, @igarag, I didn't test recently, but if you say it's ok now, I can close this issue.

Thanks for looking into it.
